spring.application.name=CloudVault

spring.datasource.url=jdbc:postgresql://localhost:5432/cloudvault
spring.datasource.username=umeshchand
spring.datasource.password=Zssuc$20
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate configurations:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT
jwt.secret=8HnT2xkP0M2g8LxYQ5X7V4uR1bN6sF9dJ3aK8mW2qZ7cE1rP5tY9uL4nH6vB2xD8
jwt.expiration=86400000

# Security
logging.level.org.springframework.security=DEBUG

# File
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=200MB
# rest configuration is already done using cli-aws configure

# S3
aws.region=us-east-1
aws.s3.bucket-name=cloud-vault-storage07


# Actuator:
management.endpoints.web.exposure.include=*

management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=CloudVault
info.app.version=1.0
info.app.author=Chief