spring.application.name=CloudVault

spring.datasource.url=jdbc:postgresql://localhost:5432/cloudvault
spring.datasource.username=umeshchand
spring.datasource.password=admin@123
spring.datasource.driver-class-name=org.postgresql.Driver

# hibernate configurations:
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

