name: CloudVault CI

on:
  push:
    branches:
      - master

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Welcome Message
        run: echo "Hello from GitHub Actions!"